# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:

  # Single deploy job since we're just deploying
  deploy:

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest

    steps:

    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
        
    - name: Get Doxygen + GraphViz + BibTeX
      run: sudo apt install doxygen graphviz texlive-latex-base


    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_CXX_COMPILER=clang++
          -DCMAKE_BUILD_TYPE=Release
          -DJABBER_BUILD_PARTICIPANT=OFF
          -DJABBER_BUILD_VIZ=OFF
          -DJABBER_BUILD_PROFILE=OFF
          -DJABBER_BUILD_OUT=OFF
          -DJABBER_BUILD_PLOT=OFF
          -DJABBER_BUILD_PSD=OFF
          -DJABBER_BUILD_APP_LIB=OFF
          -DJABBER_BUILD_TESTS=OFF
          -DJABBER_ENABLE_OPENMP=OFF
          -DJABBER_BUILD_DOCS=ON
          -S ${{ github.workspace }}

    - name: Build docs
      run: |
            cd ${{ steps.strings.outputs.build-output-dir }}
            make docs


    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{ steps.strings.outputs.build-output-dir }}/docs/html

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v5
