name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit-tests:
    runs-on: ${{ matrix.os }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false

      matrix:
        os: [ubuntu-latest]
        build_type: [Release]
        cpp_compiler: [clang++]
        omp: [on, off]

    steps:
    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Get OpenMP
      if: matrix.os == 'ubuntu-latest' && matrix.cpp_compiler == 'clang++'
      run: sudo apt install libomp-dev

    - name: Checkout w/ submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive   # or: true (non-recursive)
        fetch-depth: 0          # optional, but often nicer for versioning
      
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DJABBER_BUILD_PARTICIPANT=OFF
        -DJABBER_BUILD_VIZ=OFF
        -DJABBER_BUILD_PROFILER=OFF
        -DJABBER_BUILD_OUT=OFF
        -DJABBER_BUILD_PLOT=OFF
        -DJABBER_BUILD_PSD=OFF
        -DJABBER_BUILD_APP_LIB=ON
        -DJABBER_BUILD_TESTS=ON
        -DJABBER_ENABLE_OPENMP=${{matrix.omp}}
        -DJABBER_BUILD_DOCS=OFF
        -S ${{ github.workspace }}

    - name: Build
      # Build your program with the given configuration. Note that --config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      # Execute tests defined by the CMake configuration. Note that --build-config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest --build-config ${{ matrix.build_type }} --test-dir tests
